/*~
 * Copyright (C) 2013, 2014 George Makrydakis <george@irrequietus.eu>
 * 
 * This file is part of 'clause', a highly generic C++ meta-programming library,
 * subject to the terms and conditions of the Mozilla Public License v 2.0. If
 * a copy of the MPLv2 license text was not distributed with this file, you can
 * obtain it at: http://mozilla.org/MPL/2.0/.
 * 
 * The 'clause' library is an experimental library in active development with
 * a source code repository at: https://github.com/irrequietus/clause.git and
 * issue tracker at https://github.com/irrequietus/clause/issues.
 * 
 */

#ifndef _CLAUSE_PPMPF_VXPP_NUMBER_TUPLE_HH_
#define _CLAUSE_PPMPF_VXPP_NUMBER_TUPLE_HH_

/*~
 * @desc A macro for turning a ppmpf vxpp slot left endpoint into a ppmpf
 *       unsafe tuple of digits (i.e. comma separated digits).
 * @pfrg n: any valid slot number (i.e. 0 - 9).
 * @pexp ppmpf tuple of digits.
 */
#define PPMPF_VXPP_TN_LEFT(n) PPMPF_CAT(PPMPF_VXPP_TN_LEFT,n)()

/*~
 * @desc A macro for turning a ppmpf vxpp slot right endpoint into a ppmpf
 *       unsafe tuple of digits (i.e. comma separated digits).
 * @pfrg n: any valid slot number (i.e. 0 - 9).
 * @pexp ppmpf tuple of digits.
 */
#define PPMPF_VXPP_TN_RGHT(n) PPMPF_CAT(PPMPF_VXPP_TN_RGHT,n)()

/*~
 * @desc A macro for turning a ppmpf vxpp slot iteration item into a ppmpf
 *       unsafe tuple of digits (i.e. comma separated digits).
 * @pfrg n: any valid slot number (i.e. 0 - 9).
 * @pexp ppmpf tuple of digits.
 */
#define PPMPF_VXPP_TN_ITEM(n) PPMPF_CAT(PPMPF_VXPP_TN_ITEM,n)()

#define PPMPF_VXPP_TN_LEFT0() \
(PPMPF_VXPP_S0D4,PPMPF_VXPP_S0D3,PPMPF_VXPP_S0D2,\
PPMPF_VXPP_S0D1,PPMPF_VXPP_S0D0)

#define PPMPF_VXPP_TN_LEFT1() \
(PPMPF_VXPP_S1D4,PPMPF_VXPP_S1D3,PPMPF_VXPP_S1D2,\
PPMPF_VXPP_S1D1,PPMPF_VXPP_S1D0)

#define PPMPF_VXPP_TN_LEFT2() \
(PPMPF_VXPP_S2D4,PPMPF_VXPP_S2D3,PPMPF_VXPP_S2D2,\
PPMPF_VXPP_S2D1,PPMPF_VXPP_S2D0)

#define PPMPF_VXPP_TN_LEFT3() \
(PPMPF_VXPP_S3D4,PPMPF_VXPP_S3D3,PPMPF_VXPP_S3D2,\
PPMPF_VXPP_S3D1,PPMPF_VXPP_S3D0)

#define PPMPF_VXPP_TN_LEFT4() \
(PPMPF_VXPP_S4D4,PPMPF_VXPP_S4D3,PPMPF_VXPP_S4D2,\
PPMPF_VXPP_S4D1,PPMPF_VXPP_S4D0)

#define PPMPF_VXPP_TN_LEFT5() \
(PPMPF_VXPP_S5D4,PPMPF_VXPP_S5D3,PPMPF_VXPP_S5D2,\
PPMPF_VXPP_S5D1,PPMPF_VXPP_S5D0)

#define PPMPF_VXPP_TN_LEFT6() \
(PPMPF_VXPP_S6D4,PPMPF_VXPP_S6D3,PPMPF_VXPP_S6D2,\
PPMPF_VXPP_S6D1,PPMPF_VXPP_S6D0)

#define PPMPF_VXPP_TN_LEFT7() \
(PPMPF_VXPP_S7D4,PPMPF_VXPP_S7D3,PPMPF_VXPP_S7D2,\
PPMPF_VXPP_S7D1,PPMPF_VXPP_S7D0)

#define PPMPF_VXPP_TN_LEFT8() \
(PPMPF_VXPP_S8D4,PPMPF_VXPP_S8D3,PPMPF_VXPP_S8D2,\
PPMPF_VXPP_S8D1,PPMPF_VXPP_S8D0)

#define PPMPF_VXPP_TN_LEFT9() \
(PPMPF_VXPP_S9D4,PPMPF_VXPP_S9D3,PPMPF_VXPP_S9D2,\
PPMPF_VXPP_S9D1,PPMPF_VXPP_S9D0)

#define PPMPF_VXPP_TN_RGHT0() \
(PPMPF_VXPP_T0D4,PPMPF_VXPP_T0D3,PPMPF_VXPP_T0D2,\
PPMPF_VXPP_T0D1,PPMPF_VXPP_T0D0)

#define PPMPF_VXPP_TN_RGHT1() \
(PPMPF_VXPP_T1D4,PPMPF_VXPP_T1D3,PPMPF_VXPP_T1D2,\
PPMPF_VXPP_T1D1,PPMPF_VXPP_T1D0)

#define PPMPF_VXPP_TN_RGHT2() \
(PPMPF_VXPP_T2D4,PPMPF_VXPP_T2D3,PPMPF_VXPP_T2D2,\
PPMPF_VXPP_T2D1,PPMPF_VXPP_T2D0)

#define PPMPF_VXPP_TN_RGHT3() \
(PPMPF_VXPP_T3D4,PPMPF_VXPP_T3D3,PPMPF_VXPP_T3D2,\
PPMPF_VXPP_T3D1,PPMPF_VXPP_T3D0)

#define PPMPF_VXPP_TN_RGHT4() \
(PPMPF_VXPP_T4D4,PPMPF_VXPP_T4D3,PPMPF_VXPP_T4D2,\
PPMPF_VXPP_T4D1,PPMPF_VXPP_T4D0)

#define PPMPF_VXPP_TN_RGHT5() \
(PPMPF_VXPP_T5D4,PPMPF_VXPP_T5D3,PPMPF_VXPP_T5D2,\
PPMPF_VXPP_T5D1,PPMPF_VXPP_T5D0)

#define PPMPF_VXPP_TN_RGHT6() \
(PPMPF_VXPP_T6D4,PPMPF_VXPP_T6D3,PPMPF_VXPP_T6D2,\
PPMPF_VXPP_T6D1,PPMPF_VXPP_T6D0)

#define PPMPF_VXPP_TN_RGHT7() \
(PPMPF_VXPP_T7D4,PPMPF_VXPP_T7D3,PPMPF_VXPP_T7D2,\
PPMPF_VXPP_T7D1,PPMPF_VXPP_T7D0)

#define PPMPF_VXPP_TN_RGHT8() \
(PPMPF_VXPP_T8D4,PPMPF_VXPP_T8D3,PPMPF_VXPP_T8D2,\
PPMPF_VXPP_T8D1,PPMPF_VXPP_T8D0)

#define PPMPF_VXPP_TN_RGHT9() \
(PPMPF_VXPP_T9D4,PPMPF_VXPP_T9D3,PPMPF_VXPP_T9D2,\
PPMPF_VXPP_T9D1,PPMPF_VXPP_T9D0)

#define PPMPF_VXPP_TN_ITEM0() \
(PPMPF_VXPP_I0D4,PPMPF_VXPP_I0D3,PPMPF_VXPP_I0D2,\
PPMPF_VXPP_I0D1,PPMPF_VXPP_I0D0)

#define PPMPF_VXPP_TN_ITEM1() \
(PPMPF_VXPP_I1D4,PPMPF_VXPP_I1D3,PPMPF_VXPP_I1D2,\
PPMPF_VXPP_I1D1,PPMPF_VXPP_I1D0)

#define PPMPF_VXPP_TN_ITEM2() \
(PPMPF_VXPP_I2D4,PPMPF_VXPP_I2D3,PPMPF_VXPP_I2D2,\
PPMPF_VXPP_I2D1,PPMPF_VXPP_I2D0)

#define PPMPF_VXPP_TN_ITEM3() \
(PPMPF_VXPP_I3D4,PPMPF_VXPP_I3D3,PPMPF_VXPP_I3D2,\
PPMPF_VXPP_I3D1,PPMPF_VXPP_I3D0)

#define PPMPF_VXPP_TN_ITEM4() \
(PPMPF_VXPP_I4D4,PPMPF_VXPP_I4D3,PPMPF_VXPP_I4D2,\
PPMPF_VXPP_I4D1,PPMPF_VXPP_I4D0)

#define PPMPF_VXPP_TN_ITEM5() \
(PPMPF_VXPP_I5D4,PPMPF_VXPP_I5D3,PPMPF_VXPP_I5D2,\
PPMPF_VXPP_I5D1,PPMPF_VXPP_I5D0)

#define PPMPF_VXPP_TN_ITEM6() \
(PPMPF_VXPP_I6D4,PPMPF_VXPP_I6D3,PPMPF_VXPP_I6D2,\
PPMPF_VXPP_I6D1,PPMPF_VXPP_I6D0)

#define PPMPF_VXPP_TN_ITEM7() \
(PPMPF_VXPP_I7D4,PPMPF_VXPP_I7D3,PPMPF_VXPP_I7D2,\
PPMPF_VXPP_I7D1,PPMPF_VXPP_I7D0)

#define PPMPF_VXPP_TN_ITEM8() \
(PPMPF_VXPP_I8D4,PPMPF_VXPP_I8D3,PPMPF_VXPP_I8D2,\
PPMPF_VXPP_I8D1,PPMPF_VXPP_I8D0)

#define PPMPF_VXPP_TN_ITEM9() \
(PPMPF_VXPP_I9D4,PPMPF_VXPP_I9D3,PPMPF_VXPP_I9D2,\
PPMPF_VXPP_I9D1,PPMPF_VXPP_I9D0)

#endif /* _CLAUSE_PPMPF_VXPP_NUMBER_TUPLE_HH_ */

