/*~
 * Copyright (C) 2013, 2014 George Makrydakis <george@irrequietus.eu>
 *
 * This file is part of 'clause', a highly generic C++ meta-programming library,
 * subject to the terms and conditions of the Mozilla Public License v 2.0. If
 * a copy of the MPLv2 license text was not distributed with this file, you can
 * obtain it at: http://mozilla.org/MPL/2.0/.
 *
 * The 'clause' library is an experimental library in active development with
 * a source code repository at: https://github.com/irrequietus/clause.git and
 * issue tracker at https://github.com/irrequietus/clause/issues.
 *
 */

/*~
 * @warn This file should not be included directly in code deploying library
 *       constructs from 'clause'; it is part of preprocessor based recursive
 *       inclusions and it is limited by preprocessor-driven evaluation of
 *       constant expressions in '#if' directives.
 */

#if PPMPF_VXPP_ISSET(PPMPF_DREF(PPMPF_VXPP_SETS()))

#if   PPMPF_DIGNM(PPMPF_TUP_SIZEOF(PPMPF_VXPP_SETS())) == 2
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(0,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(1,PPMPF_VXPP_SETS())))
#elif PPMPF_DIGNM(PPMPF_TUP_SIZEOF(PPMPF_VXPP_SETS())) == 3
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(0,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(1,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(2,PPMPF_VXPP_SETS())))
#elif PPMPF_DIGNM(PPMPF_TUP_SIZEOF(PPMPF_VXPP_SETS())) == 4
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(0,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(1,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(2,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(3,PPMPF_VXPP_SETS())))
#elif PPMPF_DIGNM(PPMPF_TUP_SIZEOF(PPMPF_VXPP_SETS())) == 5
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(0,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(1,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(2,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(3,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(4,PPMPF_VXPP_SETS())))
#elif PPMPF_DIGNM(PPMPF_TUP_SIZEOF(PPMPF_VXPP_SETS())) == 6
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(0,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(1,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(2,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(3,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(4,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(5,PPMPF_VXPP_SETS())))
#elif PPMPF_DIGNM(PPMPF_TUP_SIZEOF(PPMPF_VXPP_SETS())) == 7
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(0,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(1,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(2,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(3,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(4,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(5,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(6,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(7,PPMPF_VXPP_SETS())))
#elif PPMPF_DIGNM(PPMPF_TUP_SIZEOF(PPMPF_VXPP_SETS())) == 8
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(0,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(1,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(2,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(3,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(4,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(5,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(6,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(7,PPMPF_VXPP_SETS())))
#elif PPMPF_DIGNM(PPMPF_TUP_SIZEOF(PPMPF_VXPP_SETS())) == 9
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(0,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(1,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(2,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(3,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(4,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(5,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(6,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(7,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(8,PPMPF_VXPP_SETS())))
#elif PPMPF_DIGNM(PPMPF_TUP_SIZEOF(PPMPF_VXPP_SETS())) == 10
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(0,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(1,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(2,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(3,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(4,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(5,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(6,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(7,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(8,PPMPF_VXPP_SETS())))
    #include PPMPF_VXPP_FMAPOF(PPMPF_DREF(PPMPF_VXPP_T09(9,PPMPF_VXPP_SETS())))
#endif
    #undef PPMPF_VXPP_SETS
#else
    #error PPMPF_VXPP_SETS() is not defined properly, invalid identifiers.
#endif
